server:
  port: 8080

database:
  dsn: "root:password@tcp(127.0.0.1:3306)/surveyking?charset=utf8mb4&parseTime=True&loc=Local"

jwt:
  secret: "${JWT_SECRET:change-me-in-production-min-64-chars-for-hs512-algorithm-here}"
  cookie_name: "sk-token"

storage:
  local_path: "./uploads"

ai:
  api_key: "${AI_API_KEY:}"
  base_url: "https://api.siliconflow.cn/v1"
  model: "deepseek-ai/DeepSeek-V2.5"

captcha:
  key_long: 4
  img_width: 240
  img_height: 80
